### ISSUE TITLE
Kein wirkliches Issue

### ISSUE THREAD

**Issue by MassakerGU** [schmidhorst/synology-ddns-IPv6#2]
Wie müsste ich Strato46.php anpassen dass nur IPv6 übertragen wird? Hab es selbst versucht und auch mit ChatGPT. Aber leider kenn ich mich nicht so aus. Wenn die IPv4 übertragen wird. Versuchen alle meine Anwendungen über IPv4 darauf zuzugreifen.
Vielleicht kann mir ja jemand weiter helfen.

Liebe Grüße

**Comment by schmidhorst** [comment]
Hallo,
ohne es ausprobiert zu haben, müßte das Ersetzen von

    $url = 'https://dyndns.strato.com/nic/update?hostname=' . $hostname . '&myip='; # using AUTH_BASIC
    $unchanged=true;
    $myips = $ip;
    if($ipv6 != '') { # IPv4 and IPv6 available
      $myips .= ',';
      $unchanged=str_contains($lastLogLine, $ipv6);
    }  
    if($ipv6 != '') {
      $myips .= $ipv6;
    }
    $url .=  $myips;
    $msg .= "  used url: $url\n";

    $res="nochg $ip $ipv6\n";
    # $msg .= "  last sending before $age_h h\n";
    if (! str_contains($lastLogLine, $ip) ) {
      $unchanged=false;
      # $msg .= "  new IPv4 $ip, not found in '$lastLogLine'\n";
    }
    if ( ($age_h > $ageMin_h) || (! $unchanged ) )  {

durch

    $url = 'https://dyndns.strato.com/nic/update?hostname=' . $hostname . '&myip='; # using AUTH_BASIC
    $unchanged=true;
    $myips = '';
    if($ipv6 != '') { # IPv6 available
      $myips = $ipv6;
      $unchanged=str_contains($lastLogLine, $ipv6);
    } else {
      echo("$ipv6 is not a valid IPv6 address\n");
      $msg .= "  $ipv6 is not a valid IPv6 address\n";
    }
    $url .= $myips;
    $msg .= "  used url: $url\n";
    $res="nochg $ipv6\n";
    # $msg .= "  last sending before $age_h h\n";
    if ( ($age_h > $ageMin_h) || (! $unchanged ) )  {

funktionieren.

Gemäß https://www.strato.de/faq/hosting/so-einfach-richten-sie-dyndns-fuer-ihre-domains-ein/ gilt jedoch:
```
...
myIP = 192.XXX.X.X
Optional: ja; default ist die IP Adresse des Absenders
...
```
Dies könnte heißen, dass, wenn die Synology das Kommando per IPv4 an Strato sendet, dann automatisch Deine IPv4-Absenderadresse **auch hinzugefügt wird!** Und es nur dann funktioniert, wenn per IPv6 mit dem Strato-Server kommuniziert wird. D.h. dass zwischen curl_init() und curl_exec($req) noch die Zeile
`curl_setopt($req, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V6);`
hinzugefügt werden muss.
Selbst dann, wenn alles funktioniert, dann wird vermutlich noch viele Stunden lang Deine ServerURL noch mit **IPv4- und** IPv6-Adresse aufgelöst. Auf der Kommandozeile kannst Du mittels
`nslookup <deineServerURL> dns.google`
prüfen, welche Addressen dafür z.B. beim Google-Nameserver bekannt sind. Irgendwann sollte dann nur noch Deine IPv6 zurückgeliefert werden.

**Comment by MassakerGU** [comment]
Danke, tatsächlich hab ich einfach folgendes ersetzt:
`if($ipv6 != '') {
  $myips .= $ipv6;
}
$url .=  $myips;
$msg .= "  used url: $url\n";`

Durch.

`if($ipv6 != '') {
  $myips .= $ipv6;
}
$url .=  $ipv6;
$msg .= "  used url: $url\n";`

Danke für den Tipp. Leider hatte ich es circa einen Tag vorher selbst rausbekommen. 
Verstehe sehr wenig vom Programmieren. 
Aber Danke :)
